name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.1.0
      - name: Set up Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 24.15.0
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          folder: dist
